[package]
documentation = "https://gtk-rs.org/gtk3-rs/stable/latest/docs/atk/"
categories.workspace = true
license.workspace = true
description = "Rust bindings for the ATK library"
name = "atk"
homepage.workspace = true
authors.workspace = true
readme = "README.md"
version.workspace = true
keywords = ["atk", "gtk-rs", "gnome", "accessibility"]
repository.workspace = true
exclude = ["gir-files/*"]
edition.workspace = true
rust-version.workspace = true

[lib]
name = "atk"

[features]
v2_30 = ["ffi/v2_30"]
v2_32 = ["v2_30", "ffi/v2_32"]
v2_34 = ["v2_32", "ffi/v2_34"]
v2_38 = ["v2_34", "ffi/v2_38"]
v2_46 = ["v2_38", "ffi/v2_46"]
v2_50 = ["v2_46", "ffi/v2_50"]
v2_52 = ["v2_50", "ffi/v2_52"]

[package.metadata.docs.rs]
rustdoc-args = ["--cfg", "docsrs", "--generate-link-to-definition"]

[dependencies]
libc = "0.2"
ffi = { package = "atk-sys", path = "sys" }
glib.workspace = true

[dev-dependencies]
gir-format-check = "^0.1"
