[package]
name = "gdkx11"
license.workspace = true
homepage.workspace = true
authors.workspace = true
categories.workspace = true
keywords = ["gdkx11", "gdk", "gtk-rs", "gnome", "GUI"]
readme = "README.md"
documentation = "https://gtk-rs.org/gtk3-rs/stable/latest/docs/gdkx11/"
version.workspace = true
description = "Rust bindings for the GDK X11 library"
repository.workspace = true
exclude = ["gir-files/*"]
edition.workspace = true
rust-version.workspace = true

[lib]
name = "gdkx11"

[features]
v3_24 = ["gdkx11-sys/v3_24_2"]

[package.metadata.docs.rs]
rustdoc-args = ["--cfg", "docsrs", "--generate-link-to-definition"]

[dependencies]
gdk.workspace = true
gdkx11-sys.workspace = true
gio.workspace = true
glib.workspace = true
libc = "0.2"
x11 = "2.18"

[dev-dependencies]
gir-format-check = "^0.1"
