[workspace]
default-members = [
  "atk",
  "atk/sys",
  "gdk",
  "gdk/sys",
  "gtk",
  "gtk/sys",
  "gtk3-macros",
  "examples",
]

members = [
  "atk",
  "atk/sys",
  "gdk",
  "gdk/sys",
  "gdkwayland",
  "gdkwayland/sys",
  "gdkx11",
  "gdkx11/sys",
  "gtk",
  "gtk/sys",
  "gtk3-macros",
  "examples",
]

exclude = ["gir", "checker"]
resolver = "2"

[workspace.package]
authors = ["The gtk-rs Project Developers"]
edition = "2021"
homepage = "https://gtk-rs.org/"
license = "MIT"
repository = "https://github.com/gtk-rs/gtk3-rs"
version = "0.19.0"
categories = ["api-bindings", "gui"]
rust-version = "1.92"

[workspace.dependencies]
cairo = { package = "cairo-rs", git = "https://github.com/gtk-rs/gtk-rs-core", version = "0.23.0-alpha", branch = "main" }
cairo-sys = { package = "cairo-sys-rs", git = "https://github.com/gtk-rs/gtk-rs-core", version = "0.23.0-alpha", branch = "main" }
gdk-pixbuf = { git = "https://github.com/gtk-rs/gtk-rs-core", version = "0.23.0-alpha", branch = "main" }
gdk-pixbuf-sys = { git = "https://github.com/gtk-rs/gtk-rs-core", version = "0.23.0-alpha", branch = "main" }
gio = { git = "https://github.com/gtk-rs/gtk-rs-core", version = "0.23.0-alpha", branch = "main" }
gio-sys = { git = "https://github.com/gtk-rs/gtk-rs-core", version = "0.23.0-alpha", branch = "main" }
glib = { git = "https://github.com/gtk-rs/gtk-rs-core", version = "0.23.0-alpha", branch = "main" }
glib-build-tools = { git = "https://github.com/gtk-rs/gtk-rs-core", version = "0.23.0-alpha", branch = "main" }
glib-sys = { git = "https://github.com/gtk-rs/gtk-rs-core", version = "0.23.0-alpha", branch = "main" }
gobject-sys = { git = "https://github.com/gtk-rs/gtk-rs-core", version = "0.23.0-alpha", branch = "main" }
pango = { git = "https://github.com/gtk-rs/gtk-rs-core", version = "0.23.0-alpha", branch = "main" }
pango-sys = { git = "https://github.com/gtk-rs/gtk-rs-core", version = "0.23.0-alpha", branch = "main" }
pangocairo = { git = "https://github.com/gtk-rs/gtk-rs-core", version = "0.23.0-alpha", branch = "main" }
