[workspace]
default-members = [
  "atk",
  "atk/sys",
  "gdk",
  "gdk/sys",
  "gtk",
  "gtk/sys",
  "gtk3-macros",
  "examples",
]

members = [
  "atk",
  "atk/sys",
  "gdk",
  "gdk/sys",
  "gdkwayland",
  "gdkwayland/sys",
  "gdkx11",
  "gdkx11/sys",
  "gtk",
  "gtk/sys",
  "gtk3-macros",
  "examples",
]

exclude = ["gir", "checker"]
resolver = "2"

[workspace.package]
authors = ["The gtk-rs Project Developers"]
edition = "2024"
homepage = "https://gtk-rs.org/"
license = "MIT"
repository = "https://github.com/gtk-rs/gtk3-rs"
version = "0.19.0-alpha"
categories = ["api-bindings", "gui"]
rust-version = "1.92"

[workspace.dependencies]
cairo = { package = "cairo-rs", git = "https://github.com/gtk-rs/gtk-rs-core", version = "0.23.0-alpha", branch = "main" }
cairo-sys = { package = "cairo-sys-rs", git = "https://github.com/gtk-rs/gtk-rs-core", version = "0.23.0-alpha", branch = "main" }
gdk-pixbuf = { git = "https://github.com/gtk-rs/gtk-rs-core", version = "0.23.0-alpha", branch = "main" }
gdk-pixbuf-sys = { git = "https://github.com/gtk-rs/gtk-rs-core", version = "0.23.0-alpha", branch = "main" }
gio = { git = "https://github.com/gtk-rs/gtk-rs-core", version = "0.23.0-alpha", branch = "main" }
gio-sys = { git = "https://github.com/gtk-rs/gtk-rs-core", version = "0.23.0-alpha", branch = "main" }
glib = { git = "https://github.com/gtk-rs/gtk-rs-core", version = "0.23.0-alpha", branch = "main" }
glib-build-tools = { git = "https://github.com/gtk-rs/gtk-rs-core", version = "0.23.0-alpha", branch = "main" }
glib-sys = { git = "https://github.com/gtk-rs/gtk-rs-core", version = "0.23.0-alpha", branch = "main" }
gobject-sys = { git = "https://github.com/gtk-rs/gtk-rs-core", version = "0.23.0-alpha", branch = "main" }
pango = { git = "https://github.com/gtk-rs/gtk-rs-core", version = "0.23.0-alpha", branch = "main" }
pango-sys = { git = "https://github.com/gtk-rs/gtk-rs-core", version = "0.23.0-alpha", branch = "main" }
pangocairo = { git = "https://github.com/gtk-rs/gtk-rs-core", version = "0.23.0-alpha", branch = "main" }

atk = { path = "atk", version = "0.19.0-alpha" }
atk-sys = { path = "atk/sys", version = "0.19.0-alpha" }
gdk = { path = "gdk", version = "0.19.0-alpha" }
gdk-sys = { path = "gdk/sys", version = "0.19.0-alpha" }
gdkwayland-sys = { path = "gdkwayland/sys", version = "0.19.0-alpha" }
gdkx11-sys = { path = "gdkx11/sys", version = "0.19.0-alpha" }
gtk = { path = "gtk", version = "0.19.0-alpha" }
gtk-sys = { path = "gtk/sys", version = "0.19.0-alpha" }
gtk3-macros = { path = "gtk3-macros", version = "0.19.0-alpha" }

async-channel = "2.0.0"
chrono = "0.4"
field-offset = "0.3"
futures = "0.3"
futures-channel = "0.3"
futures-util = "0.3"
gir-format-check = "^0.1"
libc = "0.2"
pkg-config = "0.3.7"
proc-macro-crate = "3.5"
proc-macro-error = "1.0"
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "2.0", features = ["full"] }
system-deps = "8"
wayland-backend = { version = "0.3.0", features = ["client_system"] }
wayland-client = "0.31"
x11 = "2.18"
