[package]
documentation = "https://gtk-rs.org/gtk3-rs/stable/latest/docs/gtk3_macros/"
categories.workspace = true
license.workspace = true
description = "Rust bindings for the GTK 3 library"
homepage.workspace = true
name = "gtk3-macros"
version.workspace = true
authors.workspace = true
edition.workspace = true
keywords = ["gtk", "gtk3", "gtk-rs", "gnome", "GUI"]
repository.workspace = true
exclude = [
    "gir-files/*",
    "src/composite_template.ui"
]
rust-version.workspace = true

[lib]
proc-macro = true

[dependencies]
proc-macro-error.workspace = true
proc-macro2.workspace = true
quote.workspace = true
syn.workspace = true
proc-macro-crate.workspace = true

[dev-dependencies]
gtk.workspace = true
