[package]
authors.workspace = true
description = "FFI bindings to libgdk-3-wayland"
homepage.workspace = true
keywords = ["gdk", "ffi", "gtk-rs", "gnome"]
license.workspace = true
name = "gdkwayland-sys"
repository.workspace = true
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[lib]
name = "gdk_wayland_sys"

[features]
v3_24 = ["gdk-sys/v3_24"]
v3_24_22 = ["v3_24"]

[dependencies]
gdk-sys.workspace = true
glib-sys.workspace = true
gobject-sys.workspace = true
libc.workspace = true

[build-dependencies]
pkg-config.workspace = true
system-deps.workspace = true

[package.metadata.docs.rs]
rustdoc-args = ["--cfg", "docsrs"]
