// This file was generated by gir (994cc1c) from gir-files (0bcaef9)
// DO NOT EDIT

#[allow(unused_imports)]
use auto::*;

pub type DateDay = u8;
pub type DateYear = u16;
pub type Time = i32;
pub type TimeSpan = i64;
