// This file was generated by gir (https://github.com/gtk-rs/gir)
// from gir-files (https://github.com/gtk-rs/gir-files)
// DO NOT EDIT

use Converter;
use FilterOutputStream;
use OutputStream;
use PollableOutputStream;
use ffi;
use glib::object::Downcast;
use glib::object::IsA;
use glib::translate::*;
use glib_ffi;
use gobject_ffi;
use std::mem;
use std::ptr;

glib_wrapper! {
    pub struct ConverterOutputStream(Object<ffi::GConverterOutputStream, ffi::GConverterOutputStreamClass>): FilterOutputStream, OutputStream, PollableOutputStream;

    match fn {
        get_type => || ffi::g_converter_output_stream_get_type(),
    }
}

impl ConverterOutputStream {
    pub fn new<P: IsA<OutputStream>, Q: IsA<Converter>>(base_stream: &P, converter: &Q) -> ConverterOutputStream {
        unsafe {
            OutputStream::from_glib_full(ffi::g_converter_output_stream_new(base_stream.to_glib_none().0, converter.to_glib_none().0)).downcast_unchecked()
        }
    }
}

pub trait ConverterOutputStreamExt {
    fn get_converter(&self) -> Option<Converter>;
}

impl<O: IsA<ConverterOutputStream>> ConverterOutputStreamExt for O {
    fn get_converter(&self) -> Option<Converter> {
        unsafe {
            from_glib_none(ffi::g_converter_output_stream_get_converter(self.to_glib_none().0))
        }
    }
}
