// This file was generated by gir (ce03df6) from gir-files (71d73f0)
// DO NOT EDIT

use ffi;
use glib::translate::*;
use glib_ffi;
use gobject_ffi;
use std::mem;
use std::ptr;

glib_wrapper! {
    pub struct EngineShape(Object<ffi::PangoEngineShape>);

    match fn {
        get_type => || ffi::pango_engine_shape_get_type(),
    }
}

impl EngineShape {}
