[package]
documentation = "https://gtk-rs.org/gtk3-rs/stable/latest/docs/gtk/"
categories.workspace = true
license.workspace = true
description = "Rust bindings for the GTK+ 3 library"
name = "gtk"
homepage.workspace = true
authors.workspace = true
readme = "README.md"
version.workspace = true
keywords = ["gtk", "gtk-rs", "gnome", "GUI"]
repository.workspace = true
build = "build.rs"
exclude = ["gir-files/*"]
edition.workspace = true
rust-version.workspace = true

[lib]
name = "gtk"

[features]
v3_22 = []
v3_24 = ["gtk-sys/v3_24"]
v3_24_1 = ["v3_24", "gtk-sys/v3_24_1"]
v3_24_8 = ["v3_24_1", "gtk-sys/v3_24_8"]
v3_24_9 = ["v3_24_8", "gtk-sys/v3_24_9"]
v3_24_11 = ["v3_24_9", "gtk-sys/v3_24_11"]
v3_24_30 = ["v3_24_11", "gtk-sys/v3_24_30"]
gio_v2_58 = ["gio/v2_58"]
gio_v2_80 = ["gio/v2_80"]
unsafe-assume-initialized = []

[package.metadata.docs.rs]
rustdoc-args = ["--cfg", "docsrs", "--generate-link-to-definition"]

[build-dependencies]
pkg-config = "0.3.7"

[dependencies]
atk.workspace = true
cairo.workspace = true
field-offset = "0.3"
futures-channel = "0.3"
gdk-pixbuf.workspace = true
gdk.workspace = true
gio.workspace = true
glib.workspace = true
gtk-sys.workspace = true
gtk3-macros.workspace = true
libc = "0.2"
pango.workspace = true

[dev-dependencies]
gir-format-check = "^0.1"
