[build-dependencies]
pkg-config = "0.3.7"
system-deps = "8"

[dependencies]
libc = "0.2"

[dependencies.cairo-sys]
workspace = true

[dependencies.gdk-pixbuf-sys]
workspace = true

[dependencies.gio-sys]
workspace = true

[dependencies.glib-sys]
workspace = true

[dependencies.gobject-sys]
workspace = true

[dependencies.pango-sys]
workspace = true

[dev-dependencies]
shell-words = "1.0.0"
tempfile = "3"

[features]
v3_24 = []

[lib]
name = "gdk_sys"

[package]
authors.workspace = true
build = "build.rs"
description = "FFI bindings to libgdk-3"
homepage.workspace = true
keywords = ["gdk", "ffi", "gtk-rs", "gnome"]
license.workspace = true
links = "gdk-3"
name = "gdk-sys"
repository.workspace = true
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[package.metadata.docs.rs]
rustdoc-args = ["--cfg", "docsrs"]
features = []
rustc-args = ["--cfg", "docsrs"]

[package.metadata.system-deps.gdk_3_0]
name = "gdk-3.0"
version = "3.22"

[package.metadata.system-deps.gdk_3_0.v3_24]
version = "3.24"
