[package]
authors.workspace = true
description = "Rust bindings of the GDK-Wayland 3 library"
documentation = "https://gtk-rs.org/gtk3-rs/stable/latest/docs/gdkwayland/"
edition.workspace = true
homepage.workspace = true
categories.workspace = true
keywords = ["gdk", "gdk-wayland", "gtk-rs", "gnome", "GUI"]
license.workspace = true
name = "gdkwayland"
readme = "README.md"
repository.workspace = true
version.workspace = true
rust-version.workspace = true

[features]
v3_24 = ["gdkwayland-sys/v3_24", "gdk/v3_24"]
v3_24_22 = ["v3_24", "gdkwayland-sys/v3_24_22"]

[package.metadata.docs.rs]
rustdoc-args = ["--cfg", "docsrs", "--generate-link-to-definition"]

[dependencies]
gdk.workspace = true
gdkwayland-sys.workspace = true
glib.workspace = true
libc.workspace = true
wayland-backend.workspace = true
wayland-client.workspace = true

[dev-dependencies]
gir-format-check.workspace = true
