on:
  push:
    branches: [master]
    paths:
      - "Cargo.lock"
      - "Cargo.toml"
      - ".github/workflows/CI.yml"
      - "atk/**"
      - "examples/**"
      - "gdk/**"
      - "gdkwayland/**"
      - "gdkx11/**"
      - "gtk/**"
      - "gtk3-macros/**"
  pull_request:
    paths:
      - "Cargo.lock"
      - "Cargo.toml"
      - ".github/workflows/CI.yml"
      - "atk/**"
      - "examples/**"
      - "gdk/**"
      - "gdkwayland/**"
      - "gdkx11/**"
      - "gtk/**"
      - "gtk3-macros/**"
  workflow_dispatch:

name: CI

jobs:
  build:
    name: ${{matrix.conf.name}} (rust ${{matrix.rust}})
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/gtk-rs/gtk3-rs/gtk3:latest
    strategy:
      matrix:
        rust:
          - stable
          - beta
          - nightly
          - "1.92"
        conf:
          - { name: "atk", features: "v2_52", test_sys: false }  # .gir file is missing `ATK_TEXT_ATTR_MARK`
          - { name: "gdk", features: "v3_24", test_sys: true }
          - { name: "gdkx11", features: "v3_24", test_sys: true }
          - { name: "gdkwayland", features: "v3_24", test_sys: false }
          - { name: "gtk", features: "v3_24_30", test_sys: false }  # a11y headers are missing some symbols
    steps:
      - uses: actions/checkout@v7
      - run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
      - uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
      - uses: actions/checkout@v7
        with:
          repository: gtk-rs/checker
          ref: main
          path: checker
        if: matrix.rust == 'nightly'
      # nightly
      # files checks
      - run: cargo build --release
        working-directory: checker
        if: matrix.rust == 'nightly'
      - run: cargo run --release -- ../${{matrix.conf.name}}
        working-directory: checker
        if: matrix.rust == 'nightly' && matrix.conf.name != 'gdkwayland'
      - run: cargo run --release -- --no-license ../${{matrix.conf.name}}/sys
        working-directory: checker
        if: matrix.rust == 'nightly' && matrix.conf.name != 'gdkwayland'
      - run: ./check_init_asserts ../${{matrix.conf.name}}
        working-directory: checker
        if: matrix.rust == 'nightly' && matrix.conf.name != 'gdkwayland'
      - name: Check doc aliases
        run: |
          python3 doc_aliases.py ../${{matrix.conf.name}}
          cd .. && git diff --exit-code
        working-directory: checker
        if: matrix.rust == 'nightly'
      # tests run
      - name: tests nightly
        run: xvfb-run --auto-servernum cargo test --manifest-path ${{ matrix.conf.name }}/Cargo.toml --features "${{ matrix.conf.features }}"
        if: matrix.rust == 'nightly'
      - name: tests sys nightly
        run: xvfb-run --auto-servernum cargo test --manifest-path ${{ matrix.conf.name }}/sys/Cargo.toml --features "${{ matrix.conf.features }}"
        if: matrix.rust == 'nightly' && matrix.conf.test_sys
      - name: build nightly
        run: cargo build --manifest-path ${{ matrix.conf.name }}/Cargo.toml --features "${{ matrix.conf.features }}"
        if: matrix.rust == 'nightly'
      # not nightly
      # clippy
      - run: rustup component add clippy
        if: matrix.rust == 'stable'
      - name: clippy ${{ matrix.conf.name }}
        run: cargo clippy --manifest-path ${{ matrix.conf.name }}/Cargo.toml --features "${{ matrix.conf.features }}" --all-targets -- -D warnings
        if: matrix.rust == 'stable'
      # tests
      - name: tests (rust ${{ matrix.rust }})
        run: xvfb-run --auto-servernum cargo test --manifest-path ${{ matrix.conf.name }}/Cargo.toml --features "${{ matrix.conf.features }}"
        if: matrix.rust != 'nightly'
      - name: tests sys
        run: xvfb-run --auto-servernum cargo test --manifest-path ${{ matrix.conf.name }}/sys/Cargo.toml --features "${{ matrix.conf.features }}"
        if: matrix.rust != 'nightly' && matrix.conf.test_sys
      - name: build
        run: cargo build --manifest-path ${{ matrix.conf.name }}/Cargo.toml --features "${{ matrix.conf.features }}"
        if: matrix.rust != 'nightly'

      - uses: bcomnes/cleanup-xvfb@v1

  build-others:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/gtk-rs/gtk3-rs/gtk3:latest
    strategy:
      matrix:
        rust:
          - stable
          - beta
          - nightly
          - "1.92"
    steps:
      - uses: actions/checkout@v7
      - uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
      # gtk3-macros
      - name: "gtk3-macros: tests"
        run: xvfb-run --auto-servernum cargo test --manifest-path gtk3-macros/Cargo.toml
      - name: "gtk3-macros: build"
        run: cargo build --manifest-path gtk3-macros/Cargo.toml
      # examples
      - name: "examples"
        run: cargo build --manifest-path examples/Cargo.toml --bins --examples --all-features

      - uses: bcomnes/cleanup-xvfb@v1

  fmt:
    name: rust fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: stable
          components: rustfmt
      - run: cargo fmt --all -- --check

  generator:
    name: regen check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          submodules: recursive
          set-safe-directory: true
      - uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: stable
      - run: git submodule update --checkout
      - run: python3 generator.py
      - run: git diff --exit-code
